on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:

  job-1:
    name: "job 1"
    runs-on: ubuntu-20.04
    steps:
      - name: "this step can fail"
        id: step1
        # continue-on-error: true
        run: "false"
      - name: "retry previous step"
        # Returns true when any previous step of a job fails. If you have a chain of dependent jobs, failure() returns true if any ancestor job fails."
        if: failure()
        # https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context
        # if: steps.step1.outcome == 'failure'
        run: "true && echo job succeeds"
